### PR TITLE
My first set of contributions if there wanted.

### PR DESCRIPTION
**Pull request by eve-moo**
I've decide to contribute to the project and this is what I've got so far.
1) Removed LUA to clean up the project a bit.
2) Removed doxygen as I don't really see the point to it and it creates a really LONG compile time every time there is a clean build.
3) Created some actually useful documentation that could be used by newcomers to learn how the project works.  I found this to be my biggest obstacle to being able to contribute!
4) Added some more exclusions to .gitignore so that simpler setups of where and how project files are arranged don't cause lots of extra unwanted file showing up in commits.  For example, I'm using netbeans and it keeps everything in the same directory so I added excludes to ignore the netbeans project files.  Netbeans also puts the compiled executables in the project directory so I added excludes for those as well as the generated cmake files.
5) I added a NPC market seeder.  I currently have it running automatically when the server starts but it could be made as a GM command as well.  The seeder runs as a worker thread because it can take quite a while to generate the entire 377809 entries.  They are listed in an xml file that I generated by parsing the NPC orders (durration of 365 days) from the eve-central dumps for the time period that Crucible was active.
6) Thread safety in logsys.  This happened once when I was creating the NPC market seeder, the worker thread was still running when the log file was closed.  By chance the worker was writing to the file and was past the log_file == null check when the main thread closed the file.  That cause a segment fault.
7) Removed the unnecessary non constant versions of 2 functions in InventoryItem.  While it's highly unlikely that they would be changed and not be compatible.  It's (in my opinion) better to have simpler code with less duplication when possible.

### CODE REVIEW

**Comment by zombu2** [comment]
I think it's great that he is taking the time and effort to fix this whole mess 

How about you create a fork of it and you keep doing what you doing I think if he keeps it up we could have an actual working server real soon 

Keep it up

**Comment by eve-moo** [comment]
I've been thinking about it and as I'm starting to add more to the documentation I'm creating maybe it would be better to create an new project just for that.  That way we can keep the actual code project clean and simple.

**Comment by VizanArkonin** [comment]
No need to. Just create a new sub-folder in /etc/ or in the root (/doc/, for instance, would make sense).
Sharding the parts in different projects is generally bad idea, as it's easy to get lost in criss-cross references and stuff.
Let's keep all parts in one bucket. They're no eggs, so nothing to break either ^_^

Cheers!

**Comment by eve-moo** [comment]
Notes on some of the additional changes I've made.  Hopefully improving server performance as well as code readability.

changed PyServiceMgr to static.  This eliminates lots of parameter passing as well as funcion calls to get the manager.
This is an example of improved code that resulted.
InventoryItemRef ore = m_Ship->GetOperator()->GetDestiny()->GetSystemManager()->GetServiceMgr()->item_factory->SpawnItem( idata );
changed to.
InventoryItemRef ore = PyServiceMgr::item_factory->SpawnItem( idata );
after the Item factory update it changed to.
InventoryItemRef ore = ItemFactory::SpawnItem( idata );

ServiceDB and descendent's changed to static.
As these had no state information (variables) it seamed redundant to have them instanced.
This was even previously foreseen in these comments...
ServiceDB PyServiceMgr::m_svcDB; //this is crap, get rid of this
    //this is a hack and needs to die:
    static ServiceDB &serviceDB() {
        return (m_svcDB);
    }
The only potential problem is in CharacterDB if the server is ever multi-threaded then the static data there may require mutex protection.  It may also be better to just check the database directly and not cache name data.

Changes to PyService derived classes regarding CallDispatcher
1) Each constructor required a call to _SetCallDispatcher, this uses more processor time.
2) Each class had a pointer to store a reference to the created CallDispatcher, using more memory.
3) Each class needed to call delete in the destructor, possible memory leak.  At least one class (ReprocessingServiceBound) forgot the delete!  By making the base class PyCallable solely responsible for storing and deleting the dispatcher memory leaks will be avoided.

**Comment by zhyrohaad** [comment]
while i appreciate all the effort you are putting into this (again), there is no way i can check in almost 500 files and 12k+ lines.
please make the commits smaller before creating a pull request.
thanks
allan

**Comment by eve-moo** [comment]
I've been keeping the commits as small as possible which is why there are so many of them.  Some of them such as changing PyServiceMgr and ItemFactory to all static necessitated changing most of the files.  Not sure how I could have done that any "smaller" other than just changing one function at a time.  But that would have just created more commits.  The total number of lines to check would be the same!
The changes I made to the database files were just find/replace of the multitude of unnecessary "INSERT INTO" statements to make the whole thing run much faster.... ofic-updates now runs in under 1 min on my system where it was about 20 min.

**Comment by eve-moo** [comment]
Oh, and over 10K of those lines are from this commit.
https://github.com/eve-moo/evemu_server/commit/d2efcb178713a87315a69d9affa9c6146e7494e1
Where I added the documentation I've been working on.  And most of that is because I'm using Syntax Highlighter to format code snippets.
http://alexgorbatchev.com/SyntaxHighlighter/

**Comment by zhyrohaad** [comment]
avainrr
"...Not sure how I could have done that any "smaller" other than just changing one function at a time. ..."  
i understand.  had the same problem when i started.  this is one thing i hate about github...once you make a pull request, it will heap EVERYTHING you've changed into that single request (including all commits after the request), which will build up rather quickly.  your actual commits are manageable, but once grouped together, it makes for a large list of changed things.  i just dont have the time to run thru them, and i cant just accept them without looking over them first.
just to put it out there, i have to verify the code you are adding will work on all possible platforms we support, with minimal problems.
again, i do appreciate your renewed interest, but with that many changes, i just cant do it.

another problem that will stop the whole thing:
i was told by a more-senior developer that this project is not ready to migrate to C++11/14.  some of my destiny rewrite uses newer code (as well as 90% of my branch), and because of that, i was not able to commit it to the official branch.  i am saying this because i see where you have done the same thing.
-allan

**Comment by Almamu** [comment]
I just have one thing to say: LUA was added to allow AI scripting so recompiling the server wouldn't be needed when making changes, so I think better leave it as is for future usage. All these commits look really good, keep up the good work ^^

**Comment by gholol** [comment]
Is there a list of implemented/unimplemented features? I want to help, but I'm not sure where to start.

**Comment by zhyrohaad** [comment]
gholol - there used to be, but the site is no longer around, so no.  there is no list of features at this time.
there also is no real direction for developers (current and wannabe), so if you want to help, just dive in.  i'd suggest starting with a server system you know rather well, and working from there.  may take a while to get used to evemu coding.
thanks

**Comment by Almamu** [comment]
You have some reasons in the thread, one being that checking all the changes to merge them is a lot, but I think there were some more reasons that I can't remember right now

**Comment by zhyrohaad** [comment]
EndlessEden, 
there are/were multiple problems with the merge.  it seems my original posts on this have disappeared.
the big reasons is a few of the 'updates' broke things, the pull request is way too large for one go, there are numerous data and file changes that i expressly asked him to NOT do, and a handfull of other things i dont remember offhand at this time.
my biggest thing was i tried his branch at that point in time, and could not get it to work.  
thats all i remember from it.
~allan

**Comment by zhyrohaad** [comment]
As stated in another post, this group of commits, and their corresponding pr, have problems that were never resolved.
Because of this, I am closing this pr.

**Pull request closed without merging**
