### PR TITLE
Destiny

### PR DESCRIPTION
**Pull request by zhyrohaad**
DestinyManager re-write.  Tracking of all ship movement, in preperation of collision detection.
Re-Write of Warp formulas, code and checks.
Fix for Warp-In bug.
Update for inclusion of object radii in distance checks.
Re-Implement of <chrono> time code, needed for my GetTimeMSeconds() function for DestinyManager::_UpdateVelocity() and DestinyManager::_Move()

NOTE:  This update will REQUIRE C++0x11 (or C++0x14) for compiling.  
for linux builds, this code is developed using GCC 4.8,  GLIBC 2.19, and KDevelop 4.
for windows users, VC13 or better is required to compile this source.

### CODE REVIEW

**Comment by Reve** [comment]
I don't think it's ok to mix stuff like this. When you are refactoring you should submit a commit only with refacotring... Also I don't think we should move to C++14 yet.. A lot off the code is legacy and uses old C libraries.

**Comment by zhyrohaad** [comment]
Reve,
Yes, I agree.
I did not realize that ALL these commits would be merged at the same time, as stated by my pull request description.
I also did not realize seperate local branches would update my origin here.  I thought they stayed seperate here, also.

As to the C++14, I am more focused on C++11, as my timers depend on <chrono>. (and that's the books I have)
I do understand a lot of the code uses old C libraries, but I am looking into updating the code (though not anytime soon).
However, if you feel we are not ready to move forward from pre-C++98, then we can revert this pull request, and I'll look into other ways to make movement work better.

**Comment by NickTaylor-** [comment]
For future reference, generally the accepted way to do a PR is to make a branch specific to what you are working on (i.e. refactoring, new module, etc.), that way you can just request the modified branch be merged. This way it keeps your commits separate, and it makes it much easier to only merge part of what you have worked on.

**Comment by Reve** [comment]
I think it will be best to revert this pull, break it into parts as NickTaylor said and then we can see much better which is the actual code change and which is refactoring. Because at the moment it's nearly impossible to distinguish between modifications and cleaning. I am glad you did some cleaning because a lot of the code was written to work but without a proper structure or coding style.

**Comment by Reve** [comment]
Also. I am working on the whole code for the core modifications. I will have almost all eve-server files modified. If we do refactoring now, it will be impossible to merge my changes. I mean a total clusterfuck :laughing:

**Comment by zhyrohaad** [comment]
Reve, I understand.
I have looked at the updates you are doing, which are very needed IMO.
From what I see (mind you, i am not a programmer), our updates are not mutually compatible, and will be almost impossible to merge, as we are working on intertwined source files. 

As NickTaylor suggested, so has Aknor.  That is what I was doing, bits and parts and doing a PR on each to get into official branch.  However, as no one with access had time to review my changes as I requested them, they sat until Aknor accepted the whole lot a few days ago.  This became the 38 file, 5k+ line clusterfuck you see as a single PR.
This is not the first time I've had to revert commits, and break them up again.
I can revert this, but I'm not sure when I'll have time to seperate the bits and pieces and re-submit.

**Pull request merged**
