### PR TITLE
Fix dependency downloading on manual compilation

### PR DESCRIPTION
**Pull request by Almamu**

### CODE REVIEW

**Comment by Almamu** [comment]
Do not merge for now, I still have to update the MySQL deps, but this also helped confirm that it compiles just fine on Linux (tested on Debian 10)

**Comment by Almamu** [comment]
Building properly for Linux, should be fine on Windows and Mac too, if anyone can check? That should be enough to merge this PR.

**Comment by jdhirst** [comment]
@Almamu will setting MariaDB dep to 10.5.9 break docker compilation? (Docker image just has 10.4).

Do you mind testing a `docker build .` on the repo?

**Comment by jdhirst** [comment]
Also, do we even still support building on Windows? 

It's quite possible a bunch of things changed in the new releases which break msvc.

With Docker now being available on Windows, native build compatibility shouldn't matter much.

**Comment by Almamu** [comment]
I have not changed the minimum versions required in the build process, I've just pointed the downloader to newer versions, so in theory it should not break any build that was already working. (that means even builds with the old mysql 5.5 libs works as shown in commit cd87ad740142f10bc505db95774f291d222c3f6a). The actual check for version is performed here: https://github.com/Almamu/evemu_server/blob/master/cmake/BuildMySQL.cmake#L7 and it's still requiring a 5.0 version or greater.

**Comment by Almamu** [comment]
About supporting building on other OSs, to be honest that's a decision for the project to make If anything. I've not used Windows builds in quite some time, but It might be interesting for some people. I guess that could be a thing to poll people? (idk If we even have enough users for that tho)

**Comment by jdhirst** [comment]
> I have not changed the minimum versions required in the build process, I've just pointed the downloader to newer versions, so in theory it should not break any build that was already working. (that means even builds with the old mysql 5.5 libs works as shown in commit [cd87ad7](https://github.com/evemuproject/evemu_server/commit/cd87ad740142f10bc505db95774f291d222c3f6a)). The actual check for version is performed here: https://github.com/Almamu/evemu_server/blob/master/cmake/BuildMySQL.cmake#L7 and it's still requiring a 5.0 version or greater.

Excellent, in that case it looks good to me!

**Comment by zhyrohaad** [comment]
Agreed.  With our active dev base, current code compilation is working as intended.
If we need to revisit for Windows users, we can do that.

**Pull request merged**
